package com.b2b.test.base;

public enum WebDriversEnum {
	LOGIN_DRIVER_TEST, EMPLOYEE_REGISTRATION_DRIVER_TEST, IMAGES_DRIVER_TEST, MENUS_DRIVER_TEST,
	MULTIPLE_TABS_DRIVER_TEST, POPUP_DRIVER_TEST, SLIDERS_DRIVER_TEST, TOOL_TIP_DRIVER_TEST,
	COLLAPSABLE_CONTENT_DRIVER_TEST
}
